### ISSUE TITLE
Allow version lock to specific Ansible Creator Execution Environment

### ISSUE THREAD

**Issue by sean-freeman** [ansible-community/ansible-lint-action#103]
**Allow version lock to specific Ansible Creator Execution Environment**

Currently static locked to v0.4.1 (one month ago), while current version is 0.5.0 (days ago):
https://github.com/ansible-community/ansible-lint-action/blob/main/action.yml#L24
https://github.com/ansible/creator-ee/releases

Allowing this to be changed during in the GH workflow file, provides some level of control over the Ansible Core and Ansible Lint versions (as was the case previously, shown below under Legacy heading).

Control over these is required for circumstances where the Ansible Collection/Roles have been written and guarenteed for working with a specific version of Ansible Core and Python, and therefore GH workflow tests should be locked accordingly.

## Legacy code:
```
jobs:
  jobname:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ansible-community/ansible-lint-action@c37fb7b4bda2c8cb18f4942716bae9f11b0dc9bc
      with:
        override-deps: |
          ansible==4.8.0
          ansible-core==2.11.6
          ansible-lint==5.2.1
```
