### ISSUE TITLE
Unable to install requirements

### ISSUE THREAD

**Issue by anth0d** [ansible-community/ansible-lint-action#31]
I am maintaining an operator-sdk project. When running `ansible-lint` locally you need to run `ansible-galaxy collection install -r requirements.yml` first. 

Maybe this is just a documentation issue but I can't see how to do that with this Action.

The result is, missing modules are not resolved when this action is run.

## Error

```console
Couldn't parse task at /github/workspace/roles/myrole/tasks/main.yml:2 (couldn't resolve module/action 'operator_sdk.util.k8s_status'. This often indicates a misspelling, missing collection, or incorrect module path.
```

## Reproduce

requirements.yml
```yaml
---
collections:
  - name: community.kubernetes
    version: "<1.0.0"
  - operator_sdk.util

```

main.yml
```yaml
- name: "update resource"
  operator_sdk.util.k8s_status:
    api_version: "foo"
    kind: "bar"
    name: "my-foo"
    namespace: "foospace"
    conditions:
      - type: Ready
        status: "True"
        reason: ReconcileSuccess
        lastHeartbeatTime: "{{ ansible_date_time.iso8601 }}"
```
